name: CI

on:
    push:
        branches: [ develop, master ]
    pull_request:
        branches: [ develop, master ]

jobs:
    build:
        runs-on: [ self-hosted, docker, linux, x64 ]

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            -   uses: actions/checkout@v3

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Install dependencies
                run: |
                    npm ci
                    npm run build
