name: CI

on:
    push:
        branches: [develop, master, next, beta, alpha]
    pull_request:
        branches: [develop, master, next, beta, alpha]

permissions:
    packages: write
    contents: write
    issues: write
    pull-requests: write

env:
    PRIMARY_NODE_VERSION: 18

jobs:
    install:
        name: Checkout and Install
        runs-on: [ self-hosted, docker, linux, x64 ]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install
              uses: ./.github/actions/install
              with:
                  node-version: ${{ env.PRIMARY_NODE_VERSION }}
    build:
        name: Build
        needs: [install]
        runs-on: [ self-hosted, docker, linux, x64 ]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install
              uses: ./.github/actions/install
              with:
                  node-version: ${{ env.PRIMARY_NODE_VERSION }}
            - name: Build
              uses: ./.github/actions/build

    test:
        name: Test
        needs: [ build ]
        runs-on: [ self-hosted, docker, linux, x64 ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install
                uses: ./.github/actions/install
                with:
                    node-version: ${{ env.PRIMARY_NODE_VERSION }}

            -   name: Build
                uses: ./.github/actions/build

            -   name: Build an image
                run: npm run cli -- build python/base

    release:
        name: Release
        needs: [build, test]
        runs-on: [ self-hosted, docker, linux, x64 ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Install
                uses: ./.github/actions/install
                with:
                    node-version: ${{ env.PRIMARY_NODE_VERSION }}

            -   name: Build
                uses: ./.github/actions/build

            -   name: Release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                run: npx semantic-release

            -   name: Webhook BETA
                uses: distributhor/workflow-webhook@v3
                if: ${{ github.ref_name == 'xxx' }}
                env:
                    webhook_url: ${{ secrets.WEBHOOK_DEV_URL }}
                    webhook_secret: ${{ secrets.WEBHOOK_DEV_SECRET }}
                    verbose: true

            -   name: Webhook PROD
                uses: distributhor/workflow-webhook@v3
                if: ${{ github.ref_name == 'xxx' }}
                env:
                    webhook_url: ${{ secrets.WEBHOOK_PROD_URL }}
                    webhook_secret: ${{ secrets.WEBHOOK_PROD_SECRET }}
                    verbose: true
