name: main

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: [ self-hosted, linux, x64 ]

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Install dependencies
                run: |
                    npm ci
                    npm run build
                    
            -   name: Push to dev
                env:
                    CONTAINER_REGISTRY: ${{ secrets.DMZ_REGISTRY }}
                    REGISTRY_USERNAME: ${{ secrets.DMZ_USERNAME }}
                    REGISTRY_PASSWORD: ${{ secrets.DMZ_PASSWORD }}
                run: npm run start
