name: main

on:
    push:
        tags:
            - v*

jobs:
    build:
        runs-on: [ self-hosted, docker, linux, x64 ]

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            -   uses: actions/checkout@v3

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Install dependencies
                run: |
                    npm ci
                    npm run build

            -   name: Push to dev
                env:
                    CONTAINER_REGISTRY: ${{ secrets.DEV_REGISTRY }},${{ secrets.DOCKER_REGISTRY }}
                    REGISTRY_USERNAME: ${{ secrets.DEV_REGISTRY_USER  }},${{ secrets.REGISTRY_USERNAME  }}
                    REGISTRY_PASSWORD: ${{ secrets.DEV_REGISTRY_PASSWORD }},${{ secrets.REGISTRY_PASSWORD }}
                run: npm run start
