name: main

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: [self-hosted, linux, x64]

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Install dependencies
                run: |
                    npm ci
                    npm run build

            # -   name: Log in to registry
            #     run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.CONTAINER_REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME  }} --password-stdin

            # -   name: Build and push images
            #     env:
            #         CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
            #         REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
            #         REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
            #     run: npm run start
                
            -   name: Log in to dev registry
                run: echo "${{ secrets.DEV_REGISTRY_PASSWORD }}" | docker login ${{ secrets.DEV_REGISTRY }} -u ${{ secrets.DEV_REGISTRY_USER  }} --password-stdin
            -   name: Push to dev
                env:
                    CONTAINER_REGISTRY: ${{ secrets.DEV_REGISTRY }}
                    REGISTRY_USERNAME: ${{ secrets.DEV_REGISTRY_USER }}
                    REGISTRY_PASSWORD: ${{ secrets.DEV_REGISTRY_PASSWORD }}
                run: npm run start
            
            -   name: Log in to DMZ registry
                run: echo "${{ secrets.DMZ_PASSWORD }}" | docker login ${{ secrets.DMZ_REGISTRY }} -u ${{ secrets.DMZ_USERNAME  }} --password-stdin
            
            -   name: Push to DMZ
                env:
                    CONTAINER_REGISTRY: ${{ secrets.DMZ_REGISTRY }}
                    REGISTRY_USERNAME: ${{ secrets.DMZ_USERNAME }}
                    REGISTRY_PASSWORD: ${{ secrets.DMZ_PASSWORD }}
                run: npm run start
